name: TaskApp CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TaskApp/TaskApp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -v

      - name: Verify pom location
        run: |
          pwd
          ls -la

      - name: Run service and bdd tests with H2 database
        run: |
          mvn test \
            -Dtest=com.project.TaskApp.service.*,com.project.TaskApp.bdd.* \
            -Dspring.datasource.url=jdbc:h2:mem:testdb \
            -Dspring.datasource.driverClassName=org.h2.Driver \
            -Dspring.datasource.username=sa \
            -Dspring.datasource.password= \
            -Dspring.jpa.database-platform=org.hibernate.dialect.H2Dialect \
            -Dspring.jpa.hibernate.ddl-auto=create-drop
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Package application
        run: mvn -B -DskipTests package

      - name: Upload packaged JAR
        uses: actions/upload-artifact@v4
        with:
          name: taskapp-jar
          path: TaskApp/TaskApp/target/*.jar

      - name: Upload test reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: TaskApp/TaskApp/target/surefire-reports/